name: CI/CD Pipeline

on:
  push:
    branches: [ hieu ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Docker
        run: |
                  sudo apt-get update
                  sudo apt-get install -y docker.io

      - name: Install Docker Compose
        run: |
                sudo apt-get install -y docker-compose

      - name: Deploy app
        run: |
          pwd
          ls -la
          git pull
          docker-compose up -d --build
